version: '3.8'

services:
  # Spring Boot Application
  student-management-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-management-backend
    ports:
      - "8080:8080"
    environment:
      # Database configuration (override for local development if needed)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres.untunudbwtyefrxdsvls
      - SPRING_DATASOURCE_PASSWORD=150211
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SERVER_PORT=8080
      # CORS configuration
      - SPRING_WEB_CORS_ALLOWED_ORIGINS=http://localhost:3000,https://student-management-system-gamma-henna.vercel.app
    networks:
      - student-management-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Local PostgreSQL for development (uncomment if needed)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: student-management-postgres
  #   environment:
  #     POSTGRES_DB: student_management
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - student-management-network

networks:
  student-management-network:
    driver: bridge

# volumes:
#   postgres_data: